(function(){
'use strict';
var REPO='momu451/mustafa-omer';
var state={bank:null,paper:null,paperIndex:0,answers:{},timer:null,left:1800,marked:false};
function el(id){return document.getElementById(id)}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function fmt(s){var m=Math.floor(s/60),r=s%60;return String(m).padStart(2,'0')+':'+String(r).padStart(2,'0')}
function badDec(v){return /\d+\.\d{3,}/.test(String(v))}
function getJSON(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}}
function setJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function stop(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function startTimer(mins){stop();state.left=mins*60;el('timer').textContent=fmt(state.left);state.timer=setInterval(function(){state.left=Math.max(0,state.left-1);el('timer').textContent=fmt(state.left);if(state.left===0){stop();mark()}},1000)}
function validatePaper(paper){if(!paper||!paper.paperTitle||!Array.isArray(paper.questions)){throw new Error('Bad paper object')};var marks=0,seenQ={};for(var i=0;i<paper.questions.length;i++){var q=paper.questions[i];marks+=Number(q.marks||0);if(seenQ[q.questionText])throw new Error('Duplicate question inside '+paper.paperTitle);seenQ[q.questionText]=true;if(q.answerType!=='multiple_choice')throw new Error('Non-MCQ in '+paper.paperTitle+' Q'+q.id);if(!Array.isArray(q.options)||q.options.length!==4)throw new Error('Bad options in '+paper.paperTitle+' Q'+q.id);var vals={};for(var j=0;j<q.options.length;j++){vals[q.options[j].value]=true;if(badDec(q.options[j].value))throw new Error('Long decimal option in '+paper.paperTitle+' Q'+q.id)}if(Object.keys(vals).length!==4)throw new Error('Duplicate option values in '+paper.paperTitle+' Q'+q.id);var hit=null;for(j=0;j<q.options.length;j++){if(q.options[j].label===q.correctAnswer)hit=q.options[j]}if(!hit||hit.value!==q.correctValue)throw new Error('Correct key mismatch in '+paper.paperTitle+' Q'+q.id);if(badDec(q.questionText)||badDec(q.correctValue))throw new Error('Long decimal in '+paper.paperTitle+' Q'+q.id)}if(marks!==Number(paper.totalMarks))throw new Error('Mark total mismatch in '+paper.paperTitle+' got '+marks+' expected '+paper.totalMarks)}
function buildBank(){if(typeof window.KS3GenerateBank!=='function')throw new Error('KS3GenerateBank did not load.');var bank=window.KS3GenerateBank();if(!bank||!Array.isArray(bank.papers)||bank.papers.length!==35)throw new Error('Generated bank did not contain 35 papers.');var papers=[];if(typeof window.KS3WeaknessProbe==='function')papers.push(window.KS3WeaknessProbe());for(var i=0;i<bank.papers.length;i++)papers.push(bank.papers[i]);bank.papers=papers;bank.version=(bank.version||'unknown')+'+v10';var seen={};for(i=0;i<bank.papers.length;i++){validatePaper(bank.papers[i]);var qs=bank.papers[i].questions;for(var j=0;j<qs.length;j++){if(seen[qs[j].questionText])throw new Error('Duplicate question across bank: '+qs[j].questionText);seen[qs[j].questionText]=true}}return bank}
function legacyHTML(){var data=(window.KS3LegacyScores&&Array.isArray(window.KS3LegacyScores.scores))?window.KS3LegacyScores.scores:[];if(!data.length)return '<div class="panel"><p><strong>Legacy scores file not loaded.</strong></p></div>';var score=0,total=0;for(var i=0;i<data.length;i++){score+=data[i].score;total+=data[i].total}var first=data.slice(0,8),later=data.slice(8),s1=0,t1=0,s2=0,t2=0;for(i=0;i<first.length;i++){s1+=first[i].score;t1+=first[i].total}for(i=0;i<later.length;i++){s2+=later[i].score;t2+=later[i].total}var html='<div class="panel" style="margin:0 0 1rem 0"><p class="eyebrow">GitHub legacy scores from screenshot</p><h3>Old completed scores</h3><p><strong>Total:</strong> '+score+'/'+total+' ('+Math.round(score/total*100)+'%). <strong>Tests 1-8:</strong> '+s1+'/'+t1+' ('+Math.round(s1/t1*100)+'%). <strong>Tests 9-20:</strong> '+s2+'/'+t2+' ('+Math.round(s2/t2*100)+'%).</p><p>These are score-only records stored in GitHub. They cannot show wrong topics because the old app did not save question-level data.</p>';for(i=0;i<data.length;i++){html+='<div class="historyItem"><span>Legacy Test '+data[i].paper+(data[i].flag?' · '+esc(data[i].flag):'')+'</span><strong>'+data[i].score+'/'+data[i].total+' ('+data[i].percent+'%)</strong></div>'}return html+'</div>'}
function newHistoryHTML(){var h=getJSON('ks3MathsScores');if(!h.length)return '<p>No new diagnostic submissions yet.</p>';var html='<div class="panel" style="margin:0 0 1rem 0"><p class="eyebrow">New diagnostic score history</p><p>These entries contain full question-level reports on this iPad.</p></div>';for(var i=0;i<h.length;i++){html+='<div class="historyItem"><span>'+esc(h[i].paperTitle)+(h[i].wrongCount!==undefined?' · '+h[i].wrongCount+' wrong':'')+'</span><strong>'+h[i].score+'/'+h[i].total+' ('+h[i].percent+'%)</strong></div>'}return html}
function renderHistory(){el('historyList').innerHTML=legacyHTML()+newHistoryHTML()}
function populate(){var html='';for(var i=0;i<state.bank.papers.length;i++){var title=state.bank.papers[i].paperTitle;html+='<option value="'+i+'">'+(i===0?'🔥 ':'')+esc(title)+'</option>'}el('paperSelect').innerHTML=html}
function progress(){if(!state.paper)return;el('progressText').textContent=Object.keys(state.answers).length+' / '+state.paper.questions.length+' answered'}
function selectedValue(q,label){for(var i=0;i<q.options.length;i++){if(q.options[i].label===label)return q.options[i].value}return null}
function renderPaper(i){stop();state.paperIndex=i;state.paper=state.bank.papers[i];state.answers={};state.marked=false;el('paperSelect').value=String(i);el('statusPanel').hidden=false;el('paperForm').hidden=false;el('actions').hidden=false;el('result').hidden=true;el('result').innerHTML='';el('paperMeta').textContent=state.paper.questions.length+' questions · '+state.paper.totalMarks+' marks · '+state.paper.timeMinutes+' minutes';el('paperTitle').textContent=state.paper.paperTitle;el('marksText').textContent=state.paper.totalMarks+' marks';var html='';for(var qi=0;qi<state.paper.questions.length;qi++){var q=state.paper.questions[qi];html+='<fieldset class="question"><div class="questionHead"><div><div class="qid">Question '+q.id+'</div><div class="topic">'+esc(q.topic)+'</div></div><span class="badge">'+q.marks+' mark'+(q.marks===1?'':'s')+'</span></div><legend class="questionText">'+esc(q.questionText)+'</legend><div class="options">';for(var oi=0;oi<q.options.length;oi++){var o=q.options[oi];html+='<label class="option"><input type="radio" name="q-'+q.id+'" value="'+esc(o.label)+'"><span class="optionLetter">'+esc(o.label)+'</span><span class="optionValue">'+esc(o.value)+'</span></label>'}html+='</div></fieldset>'}el('paperForm').innerHTML=html;var inputs=el('paperForm').querySelectorAll('input[type="radio"]');for(var k=0;k<inputs.length;k++){inputs[k].addEventListener('change',function(){var qid=this.name.replace('q-','');state.answers[qid]=this.value;var group=el('paperForm').querySelectorAll('input[name="'+this.name+'"]');for(var x=0;x<group.length;x++)group[x].closest('.option').classList.toggle('selected',group[x].checked);progress()})}progress();startTimer(state.paper.timeMinutes);window.scrollTo({top:0,behavior:'smooth'})}
function makeReport(review,score,total,percent){var topicBreakdown={},wrong=[],all=[];for(var i=0;i<review.length;i++){var r=review[i],t=r.q.topic;if(!topicBreakdown[t])topicBreakdown[t]={scored:0,available:0,lost:0,wrongQuestionIds:[]};topicBreakdown[t].available+=r.q.marks;if(r.correct){topicBreakdown[t].scored+=r.q.marks}else{topicBreakdown[t].lost+=r.q.marks;topicBreakdown[t].wrongQuestionIds.push(r.q.id);wrong.push({id:r.q.id,topic:t,marks:r.q.marks,questionText:r.q.questionText,selectedLetter:r.selected||'not answered',selectedValue:r.selected?selectedValue(r.q,r.selected):null,correctLetter:r.q.correctAnswer,correctValue:r.q.correctValue,marksLost:r.q.marks,options:r.q.options})}all.push({id:r.q.id,topic:t,marks:r.q.marks,questionText:r.q.questionText,selectedLetter:r.selected||'not answered',selectedValue:r.selected?selectedValue(r.q,r.selected):null,correctLetter:r.q.correctAnswer,correctValue:r.q.correctValue,correct:r.correct})}return{id:'ks3-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),submittedAt:new Date().toISOString(),bankVersion:state.bank.version||'unknown',paperIndex:state.paperIndex+1,paperTitle:state.paper.paperTitle,score:score,total:total,percent:percent,answered:Object.keys(state.answers).length,questionCount:state.paper.questions.length,timeRemainingSeconds:state.left,wrongQuestions:wrong,topicBreakdown:topicBreakdown,allQuestions:all}}
function reportText(report){var weak='',keys=Object.keys(report.topicBreakdown).sort(function(a,b){return report.topicBreakdown[b].lost-report.topicBreakdown[a].lost});for(var i=0;i<keys.length;i++){var k=keys[i],v=report.topicBreakdown[k];if(v.lost>0)weak+='- '+k+': '+v.scored+'/'+v.available+', lost '+v.lost+'; wrong Qs '+v.wrongQuestionIds.join(', ')+'\n'}if(!weak)weak='- None\n';var wrong='';for(i=0;i<report.wrongQuestions.length;i++){var w=report.wrongQuestions[i];wrong+='Q'+w.id+' ['+w.topic+', '+w.marks+' mark'+(w.marks===1?'':'s')+']\nQuestion: '+w.questionText+'\nSelected: '+w.selectedLetter+' '+(w.selectedValue||'')+'\nCorrect: '+w.correctLetter+' '+w.correctValue+'\nMarks lost: '+w.marksLost+'\n\n'}if(!wrong)wrong='None';return 'KS3 Maths Diagnostic Report\n'+report.paperTitle+'\nScore: '+report.score+'/'+report.total+' ('+report.percent+'%)\nSubmitted: '+report.submittedAt+'\nBank version: '+report.bankVersion+'\nAnswered: '+report.answered+'/'+report.questionCount+'\n\nTopic breakdown:\n'+weak+'\nWrong questions:\n'+wrong+'\nFull JSON:\n'+JSON.stringify(report,null,2)}
function saveReport(report){var reports=getJSON('ks3MathsReportsV2');reports.unshift(report);setJSON('ks3MathsReportsV2',reports.slice(0,100));var h=getJSON('ks3MathsScores');h.unshift({paperTitle:report.paperTitle,score:report.score,total:report.total,percent:report.percent,when:report.submittedAt,reportId:report.id,wrongCount:report.wrongQuestions.length,marksLost:report.total-report.score});setJSON('ks3MathsScores',h.slice(0,50));renderHistory()}
function copyText(text,btn){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(function(){btn.textContent='Copied diagnostic report'})}else{var ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();btn.textContent='Copied diagnostic report'}}
function mark(){if(!state.paper||state.marked)return;var score=0,review=[];for(var i=0;i<state.paper.questions.length;i++){var q=state.paper.questions[i],sel=state.answers[String(q.id)]||null,correct=sel===q.correctAnswer;if(correct)score+=q.marks;review.push({q:q,selected:sel,correct:correct})}var total=state.paper.totalMarks,percent=Math.round(score/total*100),report=makeReport(review,score,total,percent);state.marked=true;stop();saveReport(report);var topicRows='',keys=Object.keys(report.topicBreakdown).sort(function(a,b){return report.topicBreakdown[b].lost-report.topicBreakdown[a].lost});for(i=0;i<keys.length;i++){var tb=report.topicBreakdown[keys[i]];topicRows+='<tr><td>'+esc(keys[i])+'</td><td>'+tb.scored+'/'+tb.available+'</td><td>'+tb.lost+'</td><td>'+esc(tb.wrongQuestionIds.join(', ')||'-')+'</td></tr>'}var html='<p class="eyebrow">Marked diagnostic result</p><div class="scoreBig">'+score+'/'+total+'</div><h2>'+percent+'%</h2><p>'+report.wrongQuestions.length+' wrong question'+(report.wrongQuestions.length===1?'':'s')+'. Report saved on this iPad.</p><div class="actions" style="position:static;border-top:0;padding:0;margin:1rem 0"><button id="copyReportBtn" type="button">Copy full diagnostic report</button><button id="githubReportBtn" type="button" class="secondary">Open GitHub issue report</button></div><h3>Topic breakdown</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th align="left">Topic</th><th align="left">Score</th><th align="left">Lost</th><th align="left">Wrong Qs</th></tr></thead><tbody>'+topicRows+'</tbody></table></div><div class="reviewList">';for(i=0;i<review.length;i++){var r=review[i];html+='<div class="reviewItem '+(r.correct?'correct':'')+'"><strong>Q'+r.q.id+': '+(r.correct?'Correct':'Wrong')+' · '+esc(r.q.topic)+' · '+r.q.marks+' mark'+(r.q.marks===1?'':'s')+'</strong><p>'+esc(r.q.questionText)+'</p><p>Your answer: <strong>'+esc(r.selected||'not answered')+'</strong>'+(r.selected?' — '+esc(selectedValue(r.q,r.selected)||''):'')+'</p><p>Correct answer: <strong>'+esc(r.q.correctAnswer)+' — '+esc(r.q.correctValue)+'</strong></p></div>'}html+='</div>';el('result').hidden=false;el('result').innerHTML=html;el('copyReportBtn').onclick=function(){copyText(reportText(report),this)};el('githubReportBtn').onclick=function(){var title=encodeURIComponent('KS3 score: '+report.paperTitle+' — '+report.score+'/'+report.total+' ('+report.percent+'%)'),body=encodeURIComponent('```text\n'+reportText(report).slice(0,55000)+'\n```');window.open('https://github.com/'+REPO+'/issues/new?title='+title+'&body='+body,'_blank','noopener')};el('result').scrollIntoView({behavior:'smooth',block:'start'})}
function reset(){if(!state.paper)return;state.answers={};state.marked=false;el('paperForm').reset();var opts=el('paperForm').querySelectorAll('.option');for(var i=0;i<opts.length;i++)opts[i].classList.remove('selected');el('result').hidden=true;progress();startTimer(state.paper.timeMinutes)}
function boot(){try{state.bank=buildBank();populate();renderHistory();el('startBtn').onclick=function(){renderPaper(Number(el('paperSelect').value))};el('randomBtn').onclick=function(){renderPaper(1+Math.floor(Math.random()*(state.bank.papers.length-1)))};el('submitBtn').onclick=mark;el('printBtn').onclick=function(){window.print()};el('resetBtn').onclick=reset;if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=10').catch(function(){})}catch(e){document.body.innerHTML='<main class="shell"><section class="panel"><h1>App failed to load</h1><p>'+esc(e.message)+'</p><p>Refresh using ?v=10. If this persists, screenshot this error.</p></section></main>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
