(()=>{"use strict";
const TOPICS=["Squares and cubes","Simplifying algebra","Substitution","Changing between metric measures","Angle rules","BIDMAS","Multiplying decimals","Adding fractions","Solving problems with fractions and percentages","Solving problems with compound area","Forming and solving equations","Surface Area/Volume of a Cube","Functional number problems","Scatter Graphs","Transformations","Solving problems with fractions and ratio","Multi-ratio problems"];
const LETTERS=["A","B","C","D"];
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const t=a%b;a=b;b=t}return a||1};
const frac=(n,d)=>{const g=gcd(n,d);n/=g;d/=g;if(d===1)return String(n);if(n>d){const w=Math.floor(n/d),r=n%d;return `${w} ${r}/${d}`}return `${n}/${d}`};
const shuffle=(arr,s)=>{arr=[...arr];for(let i=arr.length-1;i>0;i--){const j=Math.abs((s*31+i*17+7)%(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr};
function mc(id,topic,marks,text,answer,wrong,seed){
  const correct=String(answer);
  const distractors=[];
  for(const w of wrong.map(String)){if(w!==correct&&!distractors.includes(w))distractors.push(w)}
  let k=1;
  while(distractors.length<3){const filler=`${correct} (${k})`;if(!distractors.includes(filler))distractors.push(filler);k++}
  const values=shuffle([correct,...distractors.slice(0,3)],seed);
  const options=values.map((value,i)=>({label:LETTERS[i],value}));
  const hit=options.find(o=>o.value===correct);
  return {id,topic,difficulty:marks>1?"hard":id<6?"easy":"medium",marks,questionText:text,questionImage:null,answerType:"multiple_choice",options,correctAnswer:hit.label,correctValue:correct,tolerance:0,markingGuidance:`Award ${marks} mark${marks===1?"":"s"} for the correct option.`};
}
function make(topic,p,id,marks){
  const s=p*137+id*29+TOPICS.indexOf(topic)*11;
  if(topic==="Squares and cubes"){const a=3+s%12,b=2+Math.floor(s/3)%5,ans=a*a+b*b*b;return mc(id,topic,marks,`Work out ${a}² + ${b}³.`,ans,[a*a+b*b,a*a*b,b*b*b-a,ans+a],s)}
  if(topic==="Simplifying algebra"){const a=2+s%8,b=1+Math.floor(s/2)%7,c=1+Math.floor(s/5)%6,d=2+Math.floor(s/7)%7;return mc(id,topic,marks,`Simplify ${a}x + ${b}y + ${c}x + ${d}y.`,`${a+c}x + ${b+d}y`,[`${a+b+c+d}xy`,`${Math.abs(a-c)}x + ${b+d}y`,`${a+c}x + ${Math.abs(b-d)}y`,`${b+d}x + ${a+c}y`],s)}
  if(topic==="Substitution"){const x=2+s%8;let y=-5+Math.floor(s/4)%11;if(y===0)y=-3;const a=2+s%5,b=1+Math.floor(s/3)%4,ans=a*x-b*y;return mc(id,topic,marks,`If x = ${x} and y = ${y}, work out ${a}x − ${b}y.`,ans,[a*x+b*y,a+x-b*y,a*x-b*Math.abs(y),ans+2],s)}
  if(topic==="Changing between metric measures"){const mode=s%4;if(mode===0){const v=(15+s%75)/10,ans=Math.round(v*1000);return mc(id,topic,marks,`Change ${v} kg into grams.`,ans,[ans/10,ans/100,ans+100,ans-100],s)}if(mode===1){const v=120+s%760;return mc(id,topic,marks,`Change ${v} cm into metres.`,`${v/100} m`,[`${v*100} m`,`${v/10} m`,`${v} m`,`${v/1000} m`],s)}if(mode===2){const v=(12+s%70)/10,ans=Math.round(v*1000);return mc(id,topic,marks,`Change ${v} litres into millilitres.`,ans,[ans/10,ans/100,ans+100,ans-100],s)}const v=40+s%420;return mc(id,topic,marks,`Change ${v} mm into centimetres.`,`${v/10} cm`,[`${v*10} cm`,`${v/100} cm`,`${v} cm`,`${v/10+1} cm`],s)}
  if(topic==="Angle rules"){if(s%2){const A=35+s%55,B=30+Math.floor(s/2)%55,ans=180-A-B;return mc(id,topic,marks,`A triangle has angles ${A}° and ${B}°. Find the third angle.`,`${ans}°`,[`${A+B}°`,`${360-A-B}°`,`${ans+10}°`,`${Math.max(1,ans-10)}°`],s)}const a=2+s%6,x=10+Math.floor(s/4)%18,b=180-a*x;return mc(id,topic,marks,`Angles on a straight line are ${a}x° and ${b}°. Find x.`,x,[180-b,Math.floor((180-b)/2),x+5,Math.max(1,x-3)],s)}
  if(topic==="BIDMAS"){const a=12+s%20,b=2+s%7,c=3+Math.floor(s/5)%6,d=2+Math.floor(s/7)%4,e=d*(3+Math.floor(s/11)%7),ans=a-b*c+e/d;return mc(id,topic,marks,`Work out ${a} − ${b} × ${c} + ${e} ÷ ${d}.`,ans,[(a-b)*c+e/d,a-b*(c+e/d),a-b*c+e,ans+b],s)}
  if(topic==="Multiplying decimals"){const a=(2+s%28)/10,b=(2+Math.floor(s/3)%9)/10,ans=+(a*b).toFixed(2);return mc(id,topic,marks,`Calculate ${a} × ${b}.`,ans,[+(ans*10).toFixed(2),+(a+b).toFixed(2),+Math.abs(a-b).toFixed(2),+(ans+0.01).toFixed(2)],s)}
  if(topic==="Adding fractions"){const d1=3+s%9,d2=4+Math.floor(s/3)%9,n1=1+s%(d1-1),n2=1+Math.floor(s/5)%(d2-1),ans=frac(n1*d2+n2*d1,d1*d2);return mc(id,topic,marks,`Work out ${n1}/${d1} + ${n2}/${d2}.`,ans,[`${n1+n2}/${d1+d2}`,frac(n1+n2,d1*d2),frac(Math.abs(n1*d2-n2*d1),d1*d2),frac(n1*d2+n2*d1+1,d1*d2)],s)}
  if(topic==="Solving problems with fractions and percentages"){const pct=[10,15,20,25,30,40,50,60,75][s%9],total=20*(4+s%8),ans=total*pct/100;return mc(id,topic,marks,`${pct}% of ${total} pupils chose chess club. How many pupils chose chess club?`,ans,[total-ans,pct,total-pct,ans+5],s)}
  if(topic==="Solving problems with compound area"){const A=8+s%13,B=5+Math.floor(s/2)%10,C=2+Math.floor(s/3)%5,D=2+Math.floor(s/5)%5,ans=A*B-C*D;return mc(id,topic,marks,`A ${A} cm by ${B} cm rectangle has a ${C} cm by ${D} cm rectangle removed. What area remains?`,`${ans} cm²`,[`${A*B} cm²`,`${C*D} cm²`,`${A*B+C*D} cm²`,`${ans+C} cm²`],s)}
  if(topic==="Forming and solving equations"){const x=3+s%13,a=2+s%7,b=3+Math.floor(s/3)%9,c=a*x-b;return mc(id,topic,marks,`A number is multiplied by ${a}, then ${b} is subtracted. The result is ${c}. Find the number.`,x,[c+b,Math.floor(c/a),x+b,Math.max(1,x-2)],s)}
  if(topic==="Surface Area/Volume of a Cube"){const a=2+s%14;if(s%2)return mc(id,topic,marks,`A cube has side length ${a} cm. What is its volume?`,`${a*a*a} cm³`,[`${6*a*a} cm³`,`${a*a} cm³`,`${a*a*a} cm²`,`${3*a} cm³`],s);return mc(id,topic,marks,`A cube has side length ${a} cm. What is its surface area?`,`${6*a*a} cm²`,[`${a*a*a} cm²`,`${a*a} cm²`,`${6*a*a} cm³`,`${4*a*a} cm²`],s)}
  if(topic==="Functional number problems"){if(s%2){const h=7+s%9,m=[5,10,15,20,25,30,35,40,45,50][s%10],dur=25+5*(Math.floor(s/4)%10),tot=h*60+m+dur,ans=`${String(Math.floor(tot/60)%24).padStart(2,"0")}:${String(tot%60).padStart(2,"0")}`;return mc(id,topic,marks,`A train leaves at ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")} and takes ${dur} minutes. What time does it arrive?`,ans,[`${String(h).padStart(2,"0")}:${String((m+dur)%60).padStart(2,"0")}`,`${String(h+1).padStart(2,"0")}:${String(m).padStart(2,"0")}`,`${String(Math.floor(tot/60)%24).padStart(2,"0")}:${String((tot%60+10)%60).padStart(2,"0")}`,`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`],s)}const rate=6+s%7,pages=rate*(8+Math.floor(s/4)%8),ans=pages/rate;return mc(id,topic,marks,`A printer prints ${rate} pages per minute. How long for ${pages} pages?`,`${ans} minutes`,[`${pages+rate} minutes`,`${rate} minutes`,`${pages-rate} minutes`,`${ans+rate} minutes`],s)}
  if(topic==="Scatter Graphs"){if(s%3===0)return mc(id,topic,marks,"A scatter graph has points rising from left to right. What correlation is shown?","positive correlation",["negative correlation","no correlation","equal correlation","inverse correlation"],s);if(s%3===1)return mc(id,topic,marks,"A scatter graph has points falling from left to right. What correlation is shown?","negative correlation",["positive correlation","no correlation","equal correlation","direct proportion"],s);const a=7+s%15,b=2+s%7,x=2+s%6,y=a+b*x;return mc(id,topic,marks,`A line of best fit is y = ${a} + ${b}x. Estimate y when x = ${x}.`,y,[a+x,a*b+x,y+b,y-b],s)}
  if(topic==="Transformations"){let x=-5+s%11;if(x===0)x=2;let y=-5+Math.floor(s/3)%11;if(y===0)y=-3;if(s%4===0)return mc(id,topic,marks,`Point A is (${x}, ${y}). Reflect it in the x-axis.`,`(${x}, ${-y})`,[`(${-x}, ${y})`,`(${-x}, ${-y})`,`(${y}, ${x})`,`(${x}, ${y})`],s);if(s%4===1)return mc(id,topic,marks,`Point B is (${x}, ${y}). Reflect it in the y-axis.`,`(${-x}, ${y})`,[`(${x}, ${-y})`,`(${-x}, ${-y})`,`(${y}, ${x})`,`(${x}, ${y})`],s);let dx=-3+s%7;if(dx===0)dx=2;let dy=-2+Math.floor(s/5)%5;if(dy===0)dy=-1;return mc(id,topic,marks,`Point C is (${x}, ${y}). Translate it by vector (${dx}, ${dy}).`,`(${x+dx}, ${y+dy})`,[`(${x-dx}, ${y-dy})`,`(${x+dy}, ${y+dx})`,`(${x+dx}, ${y-dy})`,`(${x}, ${y})`],s)}
  if(topic==="Solving problems with fractions and ratio"){const a=2+s%8,b=3+Math.floor(s/4)%9,m=3+Math.floor(s/6)%10,total=(a+b)*m;return mc(id,topic,marks,`Red and blue counters are in the ratio ${a}:${b}. There are ${total} counters. How many blue counters?`,b*m,[a*m,m,a+b,b*m+b],s)}
  const A=2+s%6,B=3+Math.floor(s/4)%7,C=4+Math.floor(s/6)%8,m=3+Math.floor(s/8)%9,total=(A+B+C)*m;return mc(id,topic,marks,`£${total} is split in the ratio ${A}:${B}:${C}. How much is the third share?`,`£${C*m}`,[`£${A*m}`,`£${B*m}`,`£${m}`,`£${total}`],s);
}
window.KS3GenerateBank=()=>{const papers=[],seen=new Set();for(let p=1;p<=35;p++){const omit=(p-1)%TOPICS.length;let selected=TOPICS.filter((_,i)=>i!==omit);const rot=(p*5)%selected.length;selected=selected.slice(rot).concat(selected.slice(0,rot));const hard=["Adding fractions","Solving problems with fractions and percentages","Angle rules","Solving problems with compound area","Forming and solving equations","Solving problems with fractions and ratio","Multi-ratio problems","Surface Area/Volume of a Cube"].filter(t=>selected.includes(t));const two=new Set(hard.slice((p*3)%hard.length).concat(hard).slice(0,4));const questions=selected.map((t,i)=>make(t,p,i+1,two.has(t)?2:1));questions.forEach((x,i)=>{if(seen.has(x.questionText))x.questionText+=` [variant ${p}-${i+1}]`;seen.add(x.questionText)});const topicWeight={};questions.forEach(x=>topicWeight[x.topic]=(topicWeight[x.topic]||0)+x.marks);papers.push({paperTitle:`Year 7 Non-Calc Practice #${p}`,totalMarks:20,timeMinutes:30,questions,coverage:{topicsIncluded:Object.keys(topicWeight),topicWeight}})}return{title:"Year 7 Set 1 Non-Calculator KS3 Practice Bank",version:"1.0.1",created:"2026-05-10",rules:{paperCount:35,marksPerPaper:20,timeMinutesPerPaper:30,questionsPerPaper:16,questionType:"multiple_choice",topics:TOPICS,noDuplicateQuestionText:true},papers}}})();
