(()=>{"use strict";
const ROOT=typeof window!=="undefined"?window:globalThis;
const TOPICS=["Squares and cubes","Simplifying algebra","Substitution","Changing between metric measures","Angle rules","BIDMAS","Multiplying decimals","Adding fractions","Solving problems with fractions and percentages","Solving problems with compound area","Forming and solving equations","Surface Area/Volume of a Cube","Functional number problems","Scatter Graphs","Transformations","Solving problems with fractions and ratio","Multi-ratio problems"];
const LETTERS=["A","B","C","D"];
const HARD_POOL=new Set(["Substitution","Angle rules","BIDMAS","Adding fractions","Solving problems with fractions and percentages","Solving problems with compound area","Forming and solving equations","Surface Area/Volume of a Cube","Functional number problems","Scatter Graphs","Transformations","Solving problems with fractions and ratio","Multi-ratio problems"]);
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const t=a%b;a=b;b=t}return a||1};
function frac(n,d){const g=gcd(n,d);n/=g;d/=g;if(d<0){n=-n;d=-d}if(d===1)return String(n);const sign=n<0?"-":"";n=Math.abs(n);if(n>d){const w=Math.floor(n/d),r=n%d;return `${sign}${w} ${r}/${d}`}return `${sign}${n}/${d}`}
function money(p){return `£${Math.floor(p/100)}.${String(p%100).padStart(2,"0")}`}
function timeFrom(min){return `${String(Math.floor(min/60)%24).padStart(2,"0")}:${String(min%60).padStart(2,"0")}`}
function shuffle(arr,s){arr=[...arr];for(let i=arr.length-1;i>0;i--){const j=Math.abs((s*37+i*23+11)%(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function cleanOptions(answer,wrong,seed){const correct=String(answer);const distractors=[];for(const item of wrong.map(String)){if(item!==correct&&!distractors.includes(item))distractors.push(item)}let k=1;while(distractors.length<3){const filler=`${correct} ${k}`;if(!distractors.includes(filler))distractors.push(filler);k++}const values=shuffle([correct,...distractors.slice(0,3)],seed);const options=values.map((value,i)=>({label:LETTERS[i],value}));const hit=options.find(o=>o.value===correct);if(!hit)throw new Error("Correct answer missing from options");return {options,correctAnswer:hit.label,correctValue:correct}}
function q(id,topic,marks,text,answer,wrong,seed){const m=cleanOptions(answer,wrong,seed);return {id,topic,difficulty:marks===2?"hard":id<=4?"easy":"medium",marks,questionText:text,questionImage:null,answerType:"multiple_choice",options:m.options,correctAnswer:m.correctAnswer,correctValue:m.correctValue,tolerance:0,markingGuidance:`Award ${marks} mark${marks===1?"":"s"} for the correct option. The student should still show working in their exercise book for repair marking.`}}
function make(topic,p,id,marks){const s=p*1009+id*97+TOPICS.indexOf(topic)*53;
if(topic==="Squares and cubes"){const a=7+((s+p*5)%13),b=2+((Math.floor(s/5)+2*p)%6),c=2+((Math.floor(s/7)+3*p)%8),d=1+((s+4*p)%9),ans=a*a+b*b*b-c*c+d;return q(id,topic,marks,`Calculate ${a}² + ${b}³ − ${c}² + ${d}.`,ans,[a*a+b*b-c*c+d,a*2+b*b*b-c*c+d,a*a+b*b*b+c*c+d,ans+b],s)}
if(topic==="Simplifying algebra"){const vars=[["a","b"],["x","y"],["p","q"],["m","n"]][s%4],v=vars[0],w=vars[1];const A=5+s%7,B=2+Math.floor(s/3)%6,C=2+Math.floor(s/5)%6,D=3+Math.floor(s/7)%7,E=1+Math.floor(s/11)%4;const cv=A+C-E,cw=D-B;const ans=`${cv}${v} + ${cw}${w}`;const text=`Simplify ${A}${v} - ${B}${w} + ${C}${v} + ${D}${w} - ${E}${v}.`;return q(id,topic,marks,text,ans,[`${A+B+C+D-E}${v}${w}`,`${A+C+E}${v} + ${cw}${w}`,`${cv}${v} + ${B+D}${w}`,`${cw}${v} + ${cv}${w}`],s)}
if(topic==="Substitution"){let x=-4+s%9;if(x===0)x=-3;const y=2+Math.floor(s/4)%7;const a=2+s%4,b=1+Math.floor(s/5)%4;const ans=a*y*y-b*x;return q(id,topic,marks,`If x = ${x} and y = ${y}, work out ${a}y² − ${b}x.`,ans,[a*y*2-b*x,a*y*y+b*x,a*y*y-b*Math.abs(x),ans+b],s)}
if(topic==="Changing between metric measures"){const mode=s%4;if(mode===0){const m=1+Math.floor(s/9)%4,cm=25+s%70,cut=120+Math.floor(s/5)%280,ans=m*100+cm-cut;return q(id,topic,marks,`A length of string is ${m} m ${cm} cm. ${cut} cm is cut off. How much string remains?`,`${ans} cm`,[`${ans/100} cm`,`${m*100+cm+cut} cm`,`${ans+100} cm`,`${Math.abs(ans-cut)} cm`],s)}if(mode===1){const kg=2+((s+p)%6),g=25*(5+((Math.floor(s/3)+2*p)%35)),ans=kg*1000+g;return q(id,topic,marks,`A bag has mass ${kg} kg ${g} g. Write this mass in grams.`,`${ans} g`,[`${kg+g} g`,`${kg*100+g} g`,`${ans/1000} g`,`${ans+100} g`],s)}if(mode===2){const L=1+Math.floor(s/6)%3,ml=250*(1+s%3),use=125*(1+Math.floor(s/4)%5),ans=L*1000+ml-use;return q(id,topic,marks,`A bottle contains ${L} litres ${ml} ml. ${use} ml is poured out. How much is left?`,`${ans} ml`,[`${ans/1000} ml`,`${L*1000+ml+use} ml`,`${ans+use} ml`,`${Math.abs(ans-use)} ml`],s)}const cm=30+s%140,mm=5*(1+Math.floor(s/5)%17),ans=cm*10+mm;return q(id,topic,marks,`A pencil is ${cm} cm and ${mm} mm long in total. Write this length in millimetres.`,`${ans} mm`,[`${cm+mm} mm`,`${cm*100+mm} mm`,`${ans/10} mm`,`${ans-mm} mm`],s)}
if(topic==="Angle rules"){if(marks===2){const x=10+Math.floor(s/5)%18,a=2+s%3,b=3+Math.floor(s/7)%3,c=8+Math.floor(s/11)%21;let d=180-(a+b)*x-c;if(d<5){d+=30}const angle1=a*x+c,angle2=b*x+d;return q(id,topic,marks,`Two angles on a straight line are labelled ${a}x + ${c} degrees and ${b}x + ${d} degrees. What is the larger angle?`,`${Math.max(angle1,angle2)}°`,[`${x}°`,`${Math.min(angle1,angle2)}°`,`${angle1+angle2}°`,`${Math.max(angle1,angle2)+10}°`],s)}const A=42+s%48,B=51+Math.floor(s/3)%42,ans=180-A-B;return q(id,topic,marks,`A triangle has angles ${A}° and ${B}°. Find the third angle.`,`${ans}°`,[`${A+B}°`,`${360-A-B}°`,`${ans+10}°`,`${Math.max(1,ans-10)}°`],s)}
if(topic==="BIDMAS"){const a=3+((s+p)%10),b=2+((Math.floor(s/4)+p)%7),c=3+((Math.floor(s/6)+2*p)%9),d=2+((Math.floor(s/8)+p)%6),ans=(a+b)*(a+b)-c*d+b;return q(id,topic,marks,`Calculate (${a} + ${b})² − ${c} × ${d} + ${b}.`,ans,[a+b*a+b-c*d+b,(a+b)*(a+b-c)*d+b,ans+c,ans-b],s)}
if(topic==="Multiplying decimals"){const a=+(0.3+0.1*((s+2*p)%23)).toFixed(1),b=+(0.2+0.1*((Math.floor(s/5)+3*p)%9)).toFixed(1),ans=+(a*b).toFixed(2);const obj=["mat","poster","tile","panel","rug","noticeboard","card","screen","tabletop","label"][(s+p)%10];return q(id,topic,marks,`A rectangular ${obj} is ${a} m long and ${b} m wide. What is its area?`,`${ans} m²`,[`${+(a+b).toFixed(2)} m²`,`${+(ans*10).toFixed(2)} m²`,`${+Math.abs(a-b).toFixed(2)} m²`,`${+(ans+0.1).toFixed(2)} m²`],s)}
if(topic==="Adding fractions"){let d1=3+((s+7*p)%10),d2=4+((s+11*p)%11);if(d1===d2)d2+=2;const n1=1+((s+13*p)%(d1-1)),n2=1+((Math.floor(s/4)+17*p)%(d2-1));const ans=frac(n1*d2+n2*d1,d1*d2);return q(id,topic,marks,`Work out ${n1}/${d1} + ${n2}/${d2}. Give the answer in simplest form.`,ans,[`${n1+n2}/${d1+d2}`,frac(n1+n2,d1*d2),frac(Math.abs(n1*d2-n2*d1),d1*d2),frac(n1*d2+n2*d1+1,d1*d2)],s)}
if(topic==="Solving problems with fractions and percentages"){const total=[120,140,150,160,180,200,240,280,300,360][(s+p)%10],pct=[10,15,20,25,30,35,40,50,60,75][(Math.floor(s/3)+p)%10],den=[4,5,6,8,10,12][(Math.floor(s/7)+2*p)%6];const used=total*pct/100+total/den;const ans=total-used;return q(id,topic,marks,`A Year 7 group has ${total} pupils. ${pct}% chose football and 1/${den} chose netball. The rest chose athletics. How many chose athletics?`,ans,[used,total*pct/100,total/den,total- total*pct/100],s)}
if(topic==="Solving problems with compound area"){const W=12+s%9,H=9+Math.floor(s/4)%8,w=3+Math.floor(s/6)%5,h=2+Math.floor(s/8)%5,ans=W*H-w*h;return q(id,topic,marks,`An L-shape is made by removing a ${w} cm by ${h} cm rectangle from the corner of a ${W} cm by ${H} cm rectangle. Find the area of the L-shape.`,`${ans} cm²`,[`${W*H} cm²`,`${w*h} cm²`,`${W*H+w*h} cm²`,`${ans+h} cm²`],s)}
if(topic==="Forming and solving equations"){const x=4+s%17,a=2+s%3,b=1+Math.floor(s/5)%3,c=2+Math.floor(s/7)%8,d=1+Math.floor(s/11)%6,L=a*x+c,W=b*x+d,P=2*(L+W);return q(id,topic,marks,`A rectangle has length ${a}x + ${c} cm and width ${b}x + ${d} cm. Its perimeter is ${P} cm. What is its width?`,`${W} cm`,[`${x} cm`,`${L} cm`,`${P/2} cm`,`${W+1} cm`],s)}
if(topic==="Surface Area/Volume of a Cube"){const side=2+s%19,mat=["wooden","plastic","metal","glass","toy","display","storage","model","black","white"][s%10];if(marks===2){const vol=side*side*side,sa=6*side*side;return q(id,topic,marks,`A ${mat} cube has volume ${vol} cm³. What is its surface area?`,`${sa} cm²`,[`${vol} cm²`,`${side*side} cm²`,`${4*side*side} cm²`,`${sa} cm³`],s)}return q(id,topic,marks,`A ${mat} cube has side length ${side} cm. What is its volume?`,`${side*side*side} cm³`,[`${6*side*side} cm³`,`${side*side} cm³`,`${3*side} cm³`,`${side*side*side} cm²`],s)}
if(topic==="Functional number problems"){if(marks===2){const depart=8*60+15+5*(s%10),leg1=25+5*Math.floor(s/5)%8,wait=6+Math.floor(s/7)%10,leg2=18+4*Math.floor(s/11)%9;const arrive=depart+leg1+wait+leg2;return q(id,topic,marks,`A bus leaves at ${timeFrom(depart)}. It travels for ${leg1} minutes, waits for ${wait} minutes, then travels for ${leg2} minutes. What time does it arrive?`,timeFrom(arrive),[timeFrom(depart+leg1+leg2),timeFrom(depart+leg1+wait),timeFrom(arrive+10),timeFrom(arrive-5)],s)}const item=125+25*(s%12),count=2+Math.floor(s/4)%5,paid=1000+500*Math.floor(s/9)%3,change=paid-item*count;return q(id,topic,marks,`A pen costs ${money(item)}. Sam buys ${count} pens and pays with ${money(paid)}. How much change should he get?`,money(change),[money(item*count),money(paid-item),money(change+100),money(change-25)],s)}
if(topic==="Scatter Graphs"){if(marks===2){const a=8+s%12,b=2+Math.floor(s/4)%5,x=5+Math.floor(s/7)%6,y=a+b*x;return q(id,topic,marks,`A line of best fit is y = ${a} + ${b}x. Use it to estimate y when x = ${x}.`,y,[a+x,a*b+x,y+b,y-b],s)}if(s%2){const y0=50+s%30,drop=3+Math.floor(s/5)%8;return q(id,topic,marks,`A scatter graph has points roughly at (1, ${y0}), (3, ${y0-2*drop}) and (5, ${y0-4*drop}). What type of correlation is shown?`,`negative correlation`,["positive correlation","no correlation","equal correlation","direct proportion"],s)}const y0=8+s%20,rise=2+Math.floor(s/5)%7;return q(id,topic,marks,`A scatter graph has points roughly at (1, ${y0}), (3, ${y0+2*rise}) and (5, ${y0+4*rise}). What type of correlation is shown?`,`positive correlation`,["negative correlation","no correlation","inverse correlation","zero correlation"],s)}
if(topic==="Transformations"){let x=-5+s%11;if(x===0)x=4;let y=-5+Math.floor(s/3)%11;if(y===0)y=-2;if(marks===2){const dx=-3+Math.floor(s/5)%7||2,dy=-2+Math.floor(s/7)%5||-1;const rx=-x,ry=y;return q(id,topic,marks,`Point P is (${x}, ${y}). It is reflected in the y-axis and then translated by vector (${dx}, ${dy}). What are the final coordinates?`,`(${rx+dx}, ${ry+dy})`,[`(${x+dx}, ${-y+dy})`,`(${rx-dx}, ${ry-dy})`,`(${x+dx}, ${y+dy})`,`(${rx}, ${ry})`],s)}if(s%2)return q(id,topic,marks,`Point A is (${x}, ${y}). Reflect it in the x-axis.`,`(${x}, ${-y})`,[`(${-x}, ${y})`,`(${-x}, ${-y})`,`(${y}, ${x})`,`(${x}, ${y})`],s);return q(id,topic,marks,`Point B is (${x}, ${y}). Reflect it in the y-axis.`,`(${-x}, ${y})`,[`(${x}, ${-y})`,`(${-x}, ${-y})`,`(${y}, ${x})`,`(${x}, ${y})`],s)}
if(topic==="Solving problems with fractions and ratio"){if(marks===2){const pair=[[2,3],[3,5],[4,7],[5,8],[3,7],[5,9],[4,9],[7,11],[(2+(p%3)),(5+(p%5))]][(s+p)%9],a=pair[0],b=pair[1],diff=(b-a)*(5+((Math.floor(s/9)+3*p)%13)),unit=diff/(b-a),total=(a+b)*unit;return q(id,topic,marks,`Red and blue counters are in the ratio ${a}:${b}. There are ${diff} more blue counters than red counters. How many counters are there altogether?`,total,[b*unit,a*unit,diff,a+b],s)}const pair=[[2,3],[3,4],[3,5],[4,5],[4,7],[5,8],[5,9],[6,11],[7,12],[8,13]][(s+p)%10],a=pair[0],b=pair[1],m=3+((Math.floor(s/9)+2*p)%12),total=(a+b)*m;return q(id,topic,marks,`Red and blue counters are in the ratio ${a}:${b}. There are ${total} counters. How many blue counters?`,b*m,[a*m,m,a+b,b*m+b],s)}
const A=2+s%5,B=3+Math.floor(s/4)%5,C=4+Math.floor(s/6)%6,m=3+Math.floor(s/8)%8,total=(A+B+C)*m;if(marks===2){return q(id,topic,marks,`Ali, Ben and Cara share money in the ratio ${A}:${B}:${C}. Ben receives £${B*m}. How much money is shared altogether?`,`£${total}`,[`£${A*m}`,`£${C*m}`,`£${m}`,`£${total-B*m}`],s)}return q(id,topic,marks,`£${total} is split in the ratio ${A}:${B}:${C}. How much is the third share?`,`£${C*m}`,[`£${A*m}`,`£${B*m}`,`£${m}`,`£${total}`],s)}
function chooseTopics(p){const start=(p*3)%TOPICS.length;const omitted=new Set([start,(start+6)%TOPICS.length,(start+11)%TOPICS.length]);let selected=TOPICS.filter((_,i)=>!omitted.has(i));const rot=(p*5)%selected.length;return selected.slice(rot).concat(selected.slice(0,rot))}
function validate(bank){const texts=new Set();if(bank.papers.length!==35)throw new Error("Expected 35 papers");for(const paper of bank.papers){if(paper.totalMarks!==20)throw new Error(`${paper.paperTitle} is not 20 marks`);if(paper.questions.length!==14)throw new Error(`${paper.paperTitle} does not have 14 questions`);let marks=0;for(const qu of paper.questions){marks+=qu.marks;if(!TOPICS.includes(qu.topic))throw new Error(`Invalid topic ${qu.topic}`);if(texts.has(qu.questionText))throw new Error(`Duplicate question text: ${qu.questionText}`);texts.add(qu.questionText);if(qu.answerType!=="multiple_choice")throw new Error(`Non-MCQ question ${qu.id}`);if(qu.options.length!==4)throw new Error(`Bad option count ${paper.paperTitle} Q${qu.id}`);const values=new Set(qu.options.map(o=>o.value));if(values.size!==4)throw new Error(`Duplicate option values ${paper.paperTitle} Q${qu.id}`);const hit=qu.options.find(o=>o.label===qu.correctAnswer);if(!hit||hit.value!==qu.correctValue)throw new Error(`Correct answer mismatch ${paper.paperTitle} Q${qu.id}`)}if(marks!==20)throw new Error(`${paper.paperTitle} sums to ${marks}`)}return true}
ROOT.KS3GenerateBank=()=>{const papers=[];for(let p=1;p<=35;p++){const selected=chooseTopics(p);const hardCandidates=selected.filter(t=>HARD_POOL.has(t));const start=(p*2)%hardCandidates.length;const doubled=new Set(hardCandidates.slice(start).concat(hardCandidates).slice(0,6));const questions=selected.map((topic,i)=>make(topic,p,i+1,doubled.has(topic)?2:1));const topicWeight={};questions.forEach(x=>topicWeight[x.topic]=(topicWeight[x.topic]||0)+x.marks);papers.push({paperTitle:`Year 7 Non-Calc Set 1 Practice #${p}`,totalMarks:20,timeMinutes:30,questions,coverage:{topicsIncluded:Object.keys(topicWeight),topicWeight}})}const bank={title:"Year 7 Set 1 Examiner-Grade Non-Calculator KS3 Practice Bank",version:"2.0.0",created:"2026-05-10",rules:{paperCount:35,marksPerPaper:20,timeMinutesPerPaper:30,questionsPerPaper:14,questionType:"multiple_choice",topics:TOPICS,noDuplicateQuestionText:true,setStandard:"Year 7 highest-attaining Set 1; harder multi-step non-calculator revision"},papers};validate(bank);return bank};
})();
